const fallbackData = [
	{
		name: "Luke Skywalker",
		height: "172",
		mass: "77",
		hair_color: "blond",
		skin_color: "fair",
		eye_color: "blue",
		birth_year: "19BBY",
		gender: "male",
		homeworld: "https://swapi.dev/api/planets/1/",
		films: [
			"https://swapi.dev/api/films/1/",
			"https://swapi.dev/api/films/2/",
			"https://swapi.dev/api/films/3/",
			"https://swapi.dev/api/films/6/",
		],
		species: [],
		vehicles: ["https://swapi.dev/api/vehicles/14/", "https://swapi.dev/api/vehicles/30/"],
		starships: ["https://swapi.dev/api/starships/12/", "https://swapi.dev/api/starships/22/"],
		created: "2014-12-09T13:50:51.644000Z",
		edited: "2014-12-20T21:17:56.891000Z",
		url: "https://swapi.dev/api/people/1/",
	},

	{
		name: "C-3PO",
		height: "167",
		mass: "75",
		hair_color: "n/a",
		skin_color: "gold",
		eye_color: "yellow",
		birth_year: "112BBY",
		gender: "n/a",
		homeworld: "https://swapi.dev/api/planets/1/",
		films: [
			"https://swapi.dev/api/films/1/",
			"https://swapi.dev/api/films/2/",
			"https://swapi.dev/api/films/3/",
			"https://swapi.dev/api/films/4/",
			"https://swapi.dev/api/films/5/",
			"https://swapi.dev/api/films/6/",
		],
		species: ["https://swapi.dev/api/species/2/"],
		vehicles: [],
		starships: [],
		created: "2014-12-10T15:10:51.357000Z",
		edited: "2014-12-20T21:17:50.309000Z",
		url: "https://swapi.dev/api/people/2/",
	},

	{
		name: "R2-D2",
		height: "96",
		mass: "32",
		hair_color: "n/a",
		skin_color: "white, blue",
		eye_color: "red",
		birth_year: "33BBY",
		gender: "n/a",
		homeworld: "https://swapi.dev/api/planets/8/",
		films: [
			"https://swapi.dev/api/films/1/",
			"https://swapi.dev/api/films/2/",
			"https://swapi.dev/api/films/3/",
			"https://swapi.dev/api/films/4/",
			"https://swapi.dev/api/films/5/",
			"https://swapi.dev/api/films/6/",
		],
		species: ["https://swapi.dev/api/species/2/"],
		vehicles: [],
		starships: [],
		created: "2014-12-10T15:11:50.376000Z",
		edited: "2014-12-20T21:17:50.311000Z",
		url: "https://swapi.dev/api/people/3/",
	},

	{
		name: "Darth Vader",
		height: "202",
		mass: "136",
		hair_color: "none",
		skin_color: "white",
		eye_color: "yellow",
		birth_year: "41.9BBY",
		gender: "male",
		homeworld: "https://swapi.dev/api/planets/1/",
		films: [
			"https://swapi.dev/api/films/1/",
			"https://swapi.dev/api/films/2/",
			"https://swapi.dev/api/films/3/",
			"https://swapi.dev/api/films/6/",
		],
		species: [],
		vehicles: [],
		starships: ["https://swapi.dev/api/starships/13/"],
		created: "2014-12-10T15:18:20.704000Z",
		edited: "2014-12-20T21:17:50.313000Z",
		url: "https://swapi.dev/api/people/4/",
	},

	{
		name: "Leia Organa",
		height: "150",
		mass: "49",
		hair_color: "brown",
		skin_color: "light",
		eye_color: "brown",
		birth_year: "19BBY",
		gender: "female",
		homeworld: "https://swapi.dev/api/planets/2/",
		films: [
			"https://swapi.dev/api/films/1/",
			"https://swapi.dev/api/films/2/",
			"https://swapi.dev/api/films/3/",
			"https://swapi.dev/api/films/6/",
		],
		species: [],
		vehicles: ["https://swapi.dev/api/vehicles/30/"],
		starships: [],
		created: "2014-12-10T15:20:09.791000Z",
		edited: "2014-12-20T21:17:50.315000Z",
		url: "https://swapi.dev/api/people/5/",
	},

	{
		name: "Obi-Wan Kenobi",
		height: "182",
		mass: "77",
		hair_color: "auburn, white",
		skin_color: "fair",
		eye_color: "blue-gray",
		birth_year: "57BBY",
		gender: "male",
		homeworld: "https://swapi.dev/api/planets/20/",
		films: [
			"https://swapi.dev/api/films/1/",
			"https://swapi.dev/api/films/2/",
			"https://swapi.dev/api/films/3/",
			"https://swapi.dev/api/films/4/",
			"https://swapi.dev/api/films/5/",
			"https://swapi.dev/api/films/6/",
		],
		species: [],
		vehicles: ["https://swapi.dev/api/vehicles/38/"],
		starships: [
			"https://swapi.dev/api/starships/48/",
			"https://swapi.dev/api/starships/59/",
			"https://swapi.dev/api/starships/64/",
			"https://swapi.dev/api/starships/65/",
			"https://swapi.dev/api/starships/74/",
		],
		created: "2014-12-10T16:16:29.192000Z",
		edited: "2014-12-20T21:17:50.325000Z",
		url: "https://swapi.dev/api/people/10/",
	},

	{
		name: "Wilhuff Tarkin",
		height: "180",
		mass: "unknown",
		hair_color: "auburn, grey",
		skin_color: "fair",
		eye_color: "blue",
		birth_year: "64BBY",
		gender: "male",
		homeworld: "https://swapi.dev/api/planets/21/",
		films: ["https://swapi.dev/api/films/1/", "https://swapi.dev/api/films/6/"],
		species: [],
		vehicles: [],
		starships: [],
		created: "2014-12-10T16:26:56.138000Z",
		edited: "2014-12-20T21:17:50.330000Z",
		url: "https://swapi.dev/api/people/12/",
	},

	{
		name: "Chewbacca",
		height: "228",
		mass: "112",
		hair_color: "brown",
		skin_color: "unknown",
		eye_color: "blue",
		birth_year: "200BBY",
		gender: "male",
		homeworld: "https://swapi.dev/api/planets/14/",
		films: [
			"https://swapi.dev/api/films/1/",
			"https://swapi.dev/api/films/2/",
			"https://swapi.dev/api/films/3/",
			"https://swapi.dev/api/films/6/",
		],
		species: ["https://swapi.dev/api/species/3/"],
		vehicles: ["https://swapi.dev/api/vehicles/19/"],
		starships: ["https://swapi.dev/api/starships/10/", "https://swapi.dev/api/starships/22/"],
		created: "2014-12-10T16:42:45.066000Z",
		edited: "2014-12-20T21:17:50.332000Z",
		url: "https://swapi.dev/api/people/13/",
	},

	{
		name: "Han Solo",
		height: "180",
		mass: "80",
		hair_color: "brown",
		skin_color: "fair",
		eye_color: "brown",
		birth_year: "29BBY",
		gender: "male",
		homeworld: "https://swapi.dev/api/planets/22/",
		films: [
			"https://swapi.dev/api/films/1/",
			"https://swapi.dev/api/films/2/",
			"https://swapi.dev/api/films/3/",
		],
		species: [],
		vehicles: [],
		starships: ["https://swapi.dev/api/starships/10/", "https://swapi.dev/api/starships/22/"],
		created: "2014-12-10T16:49:14.582000Z",
		edited: "2014-12-20T21:17:50.334000Z",
		url: "https://swapi.dev/api/people/14/",
	},

	{
		name: "Yoda",
		height: "66",
		mass: "17",
		hair_color: "white",
		skin_color: "green",
		eye_color: "brown",
		birth_year: "896BBY",
		gender: "male",
		homeworld: "https://swapi.dev/api/planets/28/",
		films: [
			"https://swapi.dev/api/films/2/",
			"https://swapi.dev/api/films/3/",
			"https://swapi.dev/api/films/4/",
			"https://swapi.dev/api/films/5/",
			"https://swapi.dev/api/films/6/",
		],
		species: ["https://swapi.dev/api/species/6/"],
		vehicles: [],
		starships: [],
		created: "2014-12-15T12:26:01.042000Z",
		edited: "2014-12-20T21:17:50.345000Z",
		url: "https://swapi.dev/api/people/20/",
	},

	{
		name: "Palpatine",
		height: "170",
		mass: "75",
		hair_color: "grey",
		skin_color: "pale",
		eye_color: "yellow",
		birth_year: "82BBY",
		gender: "male",
		homeworld: "https://swapi.dev/api/planets/8/",
		films: [
			"https://swapi.dev/api/films/2/",
			"https://swapi.dev/api/films/3/",
			"https://swapi.dev/api/films/4/",
			"https://swapi.dev/api/films/5/",
			"https://swapi.dev/api/films/6/",
		],
		species: [],
		vehicles: [],
		starships: [],
		created: "2014-12-15T12:48:05.971000Z",
		edited: "2014-12-20T21:17:50.347000Z",
		url: "https://swapi.dev/api/people/21/",
	},

	{
		name: "Boba Fett",
		height: "183",
		mass: "78.2",
		hair_color: "black",
		skin_color: "fair",
		eye_color: "brown",
		birth_year: "31.5BBY",
		gender: "male",
		homeworld: "https://swapi.dev/api/planets/10/",
		films: [
			"https://swapi.dev/api/films/2/",
			"https://swapi.dev/api/films/3/",
			"https://swapi.dev/api/films/5/",
		],
		species: [],
		vehicles: [],
		starships: ["https://swapi.dev/api/starships/21/"],
		created: "2014-12-15T12:49:32.457000Z",
		edited: "2014-12-20T21:17:50.349000Z",
		url: "https://swapi.dev/api/people/22/",
	},

	{
		name: "IG-88",
		height: "200",
		mass: "140",
		hair_color: "none",
		skin_color: "metal",
		eye_color: "red",
		birth_year: "15BBY",
		gender: "none",
		homeworld: "https://swapi.dev/api/planets/28/",
		films: ["https://swapi.dev/api/films/2/"],
		species: ["https://swapi.dev/api/species/2/"],
		vehicles: [],
		starships: [],
		created: "2014-12-15T12:51:10.076000Z",
		edited: "2014-12-20T21:17:50.351000Z",
		url: "https://swapi.dev/api/people/23/",
	},

	{
		name: "Darth Maul",
		height: "175",
		mass: "80",
		hair_color: "none",
		skin_color: "red",
		eye_color: "yellow",
		birth_year: "54BBY",
		gender: "male",
		homeworld: "https://swapi.dev/api/planets/36/",
		films: ["https://swapi.dev/api/films/4/"],
		species: ["https://swapi.dev/api/species/22/"],
		vehicles: ["https://swapi.dev/api/vehicles/42/"],
		starships: ["https://swapi.dev/api/starships/41/"],
		created: "2014-12-19T18:00:41.929000Z",
		edited: "2014-12-20T21:17:50.403000Z",
		url: "https://swapi.dev/api/people/44/",
	},

	{
		name: "Dooku",
		height: "193",
		mass: "80",
		hair_color: "white",
		skin_color: "fair",
		eye_color: "brown",
		birth_year: "102BBY",
		gender: "male",
		homeworld: "https://swapi.dev/api/planets/52/",
		films: ["https://swapi.dev/api/films/5/", "https://swapi.dev/api/films/6/"],
		species: ["https://swapi.dev/api/species/1/"],
		vehicles: ["https://swapi.dev/api/vehicles/55/"],
		starships: [],
		created: "2014-12-20T16:52:14.726000Z",
		edited: "2014-12-20T21:17:50.462000Z",
		url: "https://swapi.dev/api/people/67/",
	},

	{
		name: "Grievous",
		height: "216",
		mass: "159",
		hair_color: "none",
		skin_color: "brown, white",
		eye_color: "green, yellow",
		birth_year: "unknown",
		gender: "male",
		homeworld: "https://swapi.dev/api/planets/59/",
		films: ["https://swapi.dev/api/films/6/"],
		species: ["https://swapi.dev/api/species/36/"],
		vehicles: ["https://swapi.dev/api/vehicles/60/"],
		starships: ["https://swapi.dev/api/starships/74/"],
		created: "2014-12-20T19:43:53.348000Z",
		edited: "2014-12-20T21:17:50.488000Z",
		url: "https://swapi.dev/api/people/79/",
	},
	{
		name: "Tatooine",
		rotation_period: "23",
		orbital_period: "304",
		diameter: "10465",
		climate: "arid",
		gravity: "1 standard",
		terrain: "desert",
		surface_water: "1",
		population: "200000",
		residents: [
			"https://swapi.dev/api/people/1/",
			"https://swapi.dev/api/people/2/",
			"https://swapi.dev/api/people/4/",
			"https://swapi.dev/api/people/6/",
			"https://swapi.dev/api/people/7/",
			"https://swapi.dev/api/people/8/",
			"https://swapi.dev/api/people/9/",
			"https://swapi.dev/api/people/11/",
			"https://swapi.dev/api/people/43/",
			"https://swapi.dev/api/people/62/",
		],
		films: [
			"https://swapi.dev/api/films/1/",
			"https://swapi.dev/api/films/3/",
			"https://swapi.dev/api/films/4/",
			"https://swapi.dev/api/films/5/",
			"https://swapi.dev/api/films/6/",
		],
		created: "2014-12-09T13:50:49.641000Z",
		edited: "2014-12-20T20:58:18.411000Z",
		url: "https://swapi.dev/api/planets/1/",
	},
	{
		name: "unknown",
		rotation_period: "0",
		orbital_period: "0",
		diameter: "0",
		climate: "unknown",
		gravity: "unknown",
		terrain: "unknown",
		surface_water: "unknown",
		population: "unknown",
		residents: [
			"https://swapi.dev/api/people/20/",
			"https://swapi.dev/api/people/23/",
			"https://swapi.dev/api/people/29/",
			"https://swapi.dev/api/people/32/",
			"https://swapi.dev/api/people/75/",
		],
		films: [],
		created: "2014-12-15T12:25:59.569000Z",
		edited: "2014-12-20T20:58:18.466000Z",
		url: "https://swapi.dev/api/planets/28/",
	},
	{
		name: "Naboo",
		rotation_period: "26",
		orbital_period: "312",
		diameter: "12120",
		climate: "temperate",
		gravity: "1 standard",
		terrain: "grassy hills, swamps, forests, mountains",
		surface_water: "12",
		population: "4500000000",
		residents: [
			"https://swapi.dev/api/people/3/",
			"https://swapi.dev/api/people/21/",
			"https://swapi.dev/api/people/35/",
			"https://swapi.dev/api/people/36/",
			"https://swapi.dev/api/people/37/",
			"https://swapi.dev/api/people/38/",
			"https://swapi.dev/api/people/39/",
			"https://swapi.dev/api/people/42/",
			"https://swapi.dev/api/people/60/",
			"https://swapi.dev/api/people/61/",
			"https://swapi.dev/api/people/66/",
		],
		films: [
			"https://swapi.dev/api/films/3/",
			"https://swapi.dev/api/films/4/",
			"https://swapi.dev/api/films/5/",
			"https://swapi.dev/api/films/6/",
		],
		created: "2014-12-10T11:52:31.066000Z",
		edited: "2014-12-20T20:58:18.430000Z",
		url: "https://swapi.dev/api/planets/8/",
	},
	{
		name: "Stewjon",
		rotation_period: "unknown",
		orbital_period: "unknown",
		diameter: "0",
		climate: "temperate",
		gravity: "1 standard",
		terrain: "grass",
		surface_water: "unknown",
		population: "unknown",
		residents: ["https://swapi.dev/api/people/10/"],
		films: [],
		created: "2014-12-10T16:16:26.566000Z",
		edited: "2014-12-20T20:58:18.452000Z",
		url: "https://swapi.dev/api/planets/20/",
	},
	{
		name: "Alderaan",
		rotation_period: "24",
		orbital_period: "364",
		diameter: "12500",
		climate: "temperate",
		gravity: "1 standard",
		terrain: "grasslands, mountains",
		surface_water: "40",
		population: "2000000000",
		residents: [
			"https://swapi.dev/api/people/5/",
			"https://swapi.dev/api/people/68/",
			"https://swapi.dev/api/people/81/",
		],
		films: ["https://swapi.dev/api/films/1/", "https://swapi.dev/api/films/6/"],
		created: "2014-12-10T11:35:48.479000Z",
		edited: "2014-12-20T20:58:18.420000Z",
		url: "https://swapi.dev/api/planets/2/",
	},
	{
		name: "Corellia",
		rotation_period: "25",
		orbital_period: "329",
		diameter: "11000",
		climate: "temperate",
		gravity: "1 standard",
		terrain: "plains, urban, hills, forests",
		surface_water: "70",
		population: "3000000000",
		residents: ["https://swapi.dev/api/people/14/", "https://swapi.dev/api/people/18/"],
		films: [],
		created: "2014-12-10T16:49:12.453000Z",
		edited: "2014-12-20T20:58:18.456000Z",
		url: "https://swapi.dev/api/planets/22/",
	},
	{
		name: "Kalee",
		rotation_period: "23",
		orbital_period: "378",
		diameter: "13850",
		climate: "arid, temperate, tropical",
		gravity: "1",
		terrain: "rainforests, cliffs, canyons, seas",
		surface_water: "unknown",
		population: "4000000000",
		residents: ["https://swapi.dev/api/people/79/"],
		films: [],
		created: "2014-12-20T19:43:51.278000Z",
		edited: "2014-12-20T20:58:18.523000Z",
		url: "https://swapi.dev/api/planets/59/",
	},
	{
		name: "Dathomir",
		rotation_period: "24",
		orbital_period: "491",
		diameter: "10480",
		climate: "temperate",
		gravity: "0.9",
		terrain: "forests, deserts, savannas",
		surface_water: "unknown",
		population: "5200",
		residents: ["https://swapi.dev/api/people/44/"],
		films: [],
		created: "2014-12-19T18:00:40.142000Z",
		edited: "2014-12-20T20:58:18.480000Z",
		url: "https://swapi.dev/api/planets/36/",
	},
	{
		name: "Kashyyyk",
		rotation_period: "26",
		orbital_period: "381",
		diameter: "12765",
		climate: "tropical",
		gravity: "1 standard",
		terrain: "jungle, forests, lakes, rivers",
		surface_water: "60",
		population: "45000000",
		residents: ["https://swapi.dev/api/people/13/", "https://swapi.dev/api/people/80/"],
		films: ["https://swapi.dev/api/films/6/"],
		created: "2014-12-10T13:32:00.124000Z",
		edited: "2014-12-20T20:58:18.442000Z",
		url: "https://swapi.dev/api/planets/14/",
	},
	{
		title: "A New Hope",
		episode_id: 4,
		opening_crawl:
			"It is a period of civil war.\r\nRebel spaceships, striking\r\nfrom a hidden base, have won\r\ntheir first victory against\r\nthe evil Galactic Empire.\r\n\r\nDuring the battle, Rebel\r\nspies managed to steal secret\r\nplans to the Empire's\r\nultimate weapon, the DEATH\r\nSTAR, an armored space\r\nstation with enough power\r\nto destroy an entire planet.\r\n\r\nPursued by the Empire's\r\nsinister agents, Princess\r\nLeia races home aboard her\r\nstarship, custodian of the\r\nstolen plans that can save her\r\npeople and restore\r\nfreedom to the galaxy....",
		director: "George Lucas",
		producer: "Gary Kurtz, Rick McCallum",
		release_date: "1977-05-25",
		characters: [
			"https://swapi.dev/api/people/1/",
			"https://swapi.dev/api/people/2/",
			"https://swapi.dev/api/people/3/",
			"https://swapi.dev/api/people/4/",
			"https://swapi.dev/api/people/5/",
			"https://swapi.dev/api/people/6/",
			"https://swapi.dev/api/people/7/",
			"https://swapi.dev/api/people/8/",
			"https://swapi.dev/api/people/9/",
			"https://swapi.dev/api/people/10/",
			"https://swapi.dev/api/people/12/",
			"https://swapi.dev/api/people/13/",
			"https://swapi.dev/api/people/14/",
			"https://swapi.dev/api/people/15/",
			"https://swapi.dev/api/people/16/",
			"https://swapi.dev/api/people/18/",
			"https://swapi.dev/api/people/19/",
			"https://swapi.dev/api/people/81/",
		],
		planets: [
			"https://swapi.dev/api/planets/1/",
			"https://swapi.dev/api/planets/2/",
			"https://swapi.dev/api/planets/3/",
		],
		starships: [
			"https://swapi.dev/api/starships/2/",
			"https://swapi.dev/api/starships/3/",
			"https://swapi.dev/api/starships/5/",
			"https://swapi.dev/api/starships/9/",
			"https://swapi.dev/api/starships/10/",
			"https://swapi.dev/api/starships/11/",
			"https://swapi.dev/api/starships/12/",
			"https://swapi.dev/api/starships/13/",
		],
		vehicles: [
			"https://swapi.dev/api/vehicles/4/",
			"https://swapi.dev/api/vehicles/6/",
			"https://swapi.dev/api/vehicles/7/",
			"https://swapi.dev/api/vehicles/8/",
		],
		species: [
			"https://swapi.dev/api/species/1/",
			"https://swapi.dev/api/species/2/",
			"https://swapi.dev/api/species/3/",
			"https://swapi.dev/api/species/4/",
			"https://swapi.dev/api/species/5/",
		],
		created: "2014-12-10T14:23:31.880000Z",
		edited: "2014-12-20T19:49:45.256000Z",
		url: "https://swapi.dev/api/films/1/",
	},
	{
		title: "The Empire Strikes Back",
		episode_id: 5,
		opening_crawl:
			"It is a dark time for the\r\nRebellion. Although the Death\r\nStar has been destroyed,\r\nImperial troops have driven the\r\nRebel forces from their hidden\r\nbase and pursued them across\r\nthe galaxy.\r\n\r\nEvading the dreaded Imperial\r\nStarfleet, a group of freedom\r\nfighters led by Luke Skywalker\r\nhas established a new secret\r\nbase on the remote ice world\r\nof Hoth.\r\n\r\nThe evil lord Darth Vader,\r\nobsessed with finding young\r\nSkywalker, has dispatched\r\nthousands of remote probes into\r\nthe far reaches of space....",
		director: "Irvin Kershner",
		producer: "Gary Kurtz, Rick McCallum",
		release_date: "1980-05-17",
		characters: [
			"https://swapi.dev/api/people/1/",
			"https://swapi.dev/api/people/2/",
			"https://swapi.dev/api/people/3/",
			"https://swapi.dev/api/people/4/",
			"https://swapi.dev/api/people/5/",
			"https://swapi.dev/api/people/10/",
			"https://swapi.dev/api/people/13/",
			"https://swapi.dev/api/people/14/",
			"https://swapi.dev/api/people/18/",
			"https://swapi.dev/api/people/20/",
			"https://swapi.dev/api/people/21/",
			"https://swapi.dev/api/people/22/",
			"https://swapi.dev/api/people/23/",
			"https://swapi.dev/api/people/24/",
			"https://swapi.dev/api/people/25/",
			"https://swapi.dev/api/people/26/",
		],
		planets: [
			"https://swapi.dev/api/planets/4/",
			"https://swapi.dev/api/planets/5/",
			"https://swapi.dev/api/planets/6/",
			"https://swapi.dev/api/planets/27/",
		],
		starships: [
			"https://swapi.dev/api/starships/3/",
			"https://swapi.dev/api/starships/10/",
			"https://swapi.dev/api/starships/11/",
			"https://swapi.dev/api/starships/12/",
			"https://swapi.dev/api/starships/15/",
			"https://swapi.dev/api/starships/17/",
			"https://swapi.dev/api/starships/21/",
			"https://swapi.dev/api/starships/22/",
			"https://swapi.dev/api/starships/23/",
		],
		vehicles: [
			"https://swapi.dev/api/vehicles/8/",
			"https://swapi.dev/api/vehicles/14/",
			"https://swapi.dev/api/vehicles/16/",
			"https://swapi.dev/api/vehicles/18/",
			"https://swapi.dev/api/vehicles/19/",
			"https://swapi.dev/api/vehicles/20/",
		],
		species: [
			"https://swapi.dev/api/species/1/",
			"https://swapi.dev/api/species/2/",
			"https://swapi.dev/api/species/3/",
			"https://swapi.dev/api/species/6/",
			"https://swapi.dev/api/species/7/",
		],
		created: "2014-12-12T11:26:24.656000Z",
		edited: "2014-12-15T13:07:53.386000Z",
		url: "https://swapi.dev/api/films/2/",
	},
	{
		title: "Return of the Jedi",
		episode_id: 6,
		opening_crawl:
			"Luke Skywalker has returned to\r\nhis home planet of Tatooine in\r\nan attempt to rescue his\r\nfriend Han Solo from the\r\nclutches of the vile gangster\r\nJabba the Hutt.\r\n\r\nLittle does Luke know that the\r\nGALACTIC EMPIRE has secretly\r\nbegun construction on a new\r\narmored space station even\r\nmore powerful than the first\r\ndreaded Death Star.\r\n\r\nWhen completed, this ultimate\r\nweapon will spell certain doom\r\nfor the small band of rebels\r\nstruggling to restore freedom\r\nto the galaxy...",
		director: "Richard Marquand",
		producer: "Howard G. Kazanjian, George Lucas, Rick McCallum",
		release_date: "1983-05-25",
		characters: [
			"https://swapi.dev/api/people/1/",
			"https://swapi.dev/api/people/2/",
			"https://swapi.dev/api/people/3/",
			"https://swapi.dev/api/people/4/",
			"https://swapi.dev/api/people/5/",
			"https://swapi.dev/api/people/10/",
			"https://swapi.dev/api/people/13/",
			"https://swapi.dev/api/people/14/",
			"https://swapi.dev/api/people/16/",
			"https://swapi.dev/api/people/18/",
			"https://swapi.dev/api/people/20/",
			"https://swapi.dev/api/people/21/",
			"https://swapi.dev/api/people/22/",
			"https://swapi.dev/api/people/25/",
			"https://swapi.dev/api/people/27/",
			"https://swapi.dev/api/people/28/",
			"https://swapi.dev/api/people/29/",
			"https://swapi.dev/api/people/30/",
			"https://swapi.dev/api/people/31/",
			"https://swapi.dev/api/people/45/",
		],
		planets: [
			"https://swapi.dev/api/planets/1/",
			"https://swapi.dev/api/planets/5/",
			"https://swapi.dev/api/planets/7/",
			"https://swapi.dev/api/planets/8/",
			"https://swapi.dev/api/planets/9/",
		],
		starships: [
			"https://swapi.dev/api/starships/2/",
			"https://swapi.dev/api/starships/3/",
			"https://swapi.dev/api/starships/10/",
			"https://swapi.dev/api/starships/11/",
			"https://swapi.dev/api/starships/12/",
			"https://swapi.dev/api/starships/15/",
			"https://swapi.dev/api/starships/17/",
			"https://swapi.dev/api/starships/22/",
			"https://swapi.dev/api/starships/23/",
			"https://swapi.dev/api/starships/27/",
			"https://swapi.dev/api/starships/28/",
			"https://swapi.dev/api/starships/29/",
		],
		vehicles: [
			"https://swapi.dev/api/vehicles/8/",
			"https://swapi.dev/api/vehicles/16/",
			"https://swapi.dev/api/vehicles/18/",
			"https://swapi.dev/api/vehicles/19/",
			"https://swapi.dev/api/vehicles/24/",
			"https://swapi.dev/api/vehicles/25/",
			"https://swapi.dev/api/vehicles/26/",
			"https://swapi.dev/api/vehicles/30/",
		],
		species: [
			"https://swapi.dev/api/species/1/",
			"https://swapi.dev/api/species/2/",
			"https://swapi.dev/api/species/3/",
			"https://swapi.dev/api/species/5/",
			"https://swapi.dev/api/species/6/",
			"https://swapi.dev/api/species/8/",
			"https://swapi.dev/api/species/9/",
			"https://swapi.dev/api/species/10/",
			"https://swapi.dev/api/species/15/",
		],
		created: "2014-12-18T10:39:33.255000Z",
		edited: "2014-12-20T09:48:37.462000Z",
		url: "https://swapi.dev/api/films/3/",
	},
	{
		title: "The Phantom Menace",
		episode_id: 1,
		opening_crawl:
			"Turmoil has engulfed the\r\nGalactic Republic. The taxation\r\nof trade routes to outlying star\r\nsystems is in dispute.\r\n\r\nHoping to resolve the matter\r\nwith a blockade of deadly\r\nbattleships, the greedy Trade\r\nFederation has stopped all\r\nshipping to the small planet\r\nof Naboo.\r\n\r\nWhile the Congress of the\r\nRepublic endlessly debates\r\nthis alarming chain of events,\r\nthe Supreme Chancellor has\r\nsecretly dispatched two Jedi\r\nKnights, the guardians of\r\npeace and justice in the\r\ngalaxy, to settle the conflict....",
		director: "George Lucas",
		producer: "Rick McCallum",
		release_date: "1999-05-19",
		characters: [
			"https://swapi.dev/api/people/2/",
			"https://swapi.dev/api/people/3/",
			"https://swapi.dev/api/people/10/",
			"https://swapi.dev/api/people/11/",
			"https://swapi.dev/api/people/16/",
			"https://swapi.dev/api/people/20/",
			"https://swapi.dev/api/people/21/",
			"https://swapi.dev/api/people/32/",
			"https://swapi.dev/api/people/33/",
			"https://swapi.dev/api/people/34/",
			"https://swapi.dev/api/people/35/",
			"https://swapi.dev/api/people/36/",
			"https://swapi.dev/api/people/37/",
			"https://swapi.dev/api/people/38/",
			"https://swapi.dev/api/people/39/",
			"https://swapi.dev/api/people/40/",
			"https://swapi.dev/api/people/41/",
			"https://swapi.dev/api/people/42/",
			"https://swapi.dev/api/people/43/",
			"https://swapi.dev/api/people/44/",
			"https://swapi.dev/api/people/46/",
			"https://swapi.dev/api/people/47/",
			"https://swapi.dev/api/people/48/",
			"https://swapi.dev/api/people/49/",
			"https://swapi.dev/api/people/50/",
			"https://swapi.dev/api/people/51/",
			"https://swapi.dev/api/people/52/",
			"https://swapi.dev/api/people/53/",
			"https://swapi.dev/api/people/54/",
			"https://swapi.dev/api/people/55/",
			"https://swapi.dev/api/people/56/",
			"https://swapi.dev/api/people/57/",
			"https://swapi.dev/api/people/58/",
			"https://swapi.dev/api/people/59/",
		],
		planets: [
			"https://swapi.dev/api/planets/1/",
			"https://swapi.dev/api/planets/8/",
			"https://swapi.dev/api/planets/9/",
		],
		starships: [
			"https://swapi.dev/api/starships/31/",
			"https://swapi.dev/api/starships/32/",
			"https://swapi.dev/api/starships/39/",
			"https://swapi.dev/api/starships/40/",
			"https://swapi.dev/api/starships/41/",
		],
		vehicles: [
			"https://swapi.dev/api/vehicles/33/",
			"https://swapi.dev/api/vehicles/34/",
			"https://swapi.dev/api/vehicles/35/",
			"https://swapi.dev/api/vehicles/36/",
			"https://swapi.dev/api/vehicles/37/",
			"https://swapi.dev/api/vehicles/38/",
			"https://swapi.dev/api/vehicles/42/",
		],
		species: [
			"https://swapi.dev/api/species/1/",
			"https://swapi.dev/api/species/2/",
			"https://swapi.dev/api/species/6/",
			"https://swapi.dev/api/species/11/",
			"https://swapi.dev/api/species/12/",
			"https://swapi.dev/api/species/13/",
			"https://swapi.dev/api/species/14/",
			"https://swapi.dev/api/species/15/",
			"https://swapi.dev/api/species/16/",
			"https://swapi.dev/api/species/17/",
			"https://swapi.dev/api/species/18/",
			"https://swapi.dev/api/species/19/",
			"https://swapi.dev/api/species/20/",
			"https://swapi.dev/api/species/21/",
			"https://swapi.dev/api/species/22/",
			"https://swapi.dev/api/species/23/",
			"https://swapi.dev/api/species/24/",
			"https://swapi.dev/api/species/25/",
			"https://swapi.dev/api/species/26/",
			"https://swapi.dev/api/species/27/",
		],
		created: "2014-12-19T16:52:55.740000Z",
		edited: "2014-12-20T10:54:07.216000Z",
		url: "https://swapi.dev/api/films/4/",
	},
	{
		title: "Attack of the Clones",
		episode_id: 2,
		opening_crawl:
			"There is unrest in the Galactic\r\nSenate. Several thousand solar\r\nsystems have declared their\r\nintentions to leave the Republic.\r\n\r\nThis separatist movement,\r\nunder the leadership of the\r\nmysterious Count Dooku, has\r\nmade it difficult for the limited\r\nnumber of Jedi Knights to maintain \r\npeace and order in the galaxy.\r\n\r\nSenator Amidala, the former\r\nQueen of Naboo, is returning\r\nto the Galactic Senate to vote\r\non the critical issue of creating\r\nan ARMY OF THE REPUBLIC\r\nto assist the overwhelmed\r\nJedi....",
		director: "George Lucas",
		producer: "Rick McCallum",
		release_date: "2002-05-16",
		characters: [
			"https://swapi.dev/api/people/2/",
			"https://swapi.dev/api/people/3/",
			"https://swapi.dev/api/people/6/",
			"https://swapi.dev/api/people/7/",
			"https://swapi.dev/api/people/10/",
			"https://swapi.dev/api/people/11/",
			"https://swapi.dev/api/people/20/",
			"https://swapi.dev/api/people/21/",
			"https://swapi.dev/api/people/22/",
			"https://swapi.dev/api/people/33/",
			"https://swapi.dev/api/people/35/",
			"https://swapi.dev/api/people/36/",
			"https://swapi.dev/api/people/40/",
			"https://swapi.dev/api/people/43/",
			"https://swapi.dev/api/people/46/",
			"https://swapi.dev/api/people/51/",
			"https://swapi.dev/api/people/52/",
			"https://swapi.dev/api/people/53/",
			"https://swapi.dev/api/people/58/",
			"https://swapi.dev/api/people/59/",
			"https://swapi.dev/api/people/60/",
			"https://swapi.dev/api/people/61/",
			"https://swapi.dev/api/people/62/",
			"https://swapi.dev/api/people/63/",
			"https://swapi.dev/api/people/64/",
			"https://swapi.dev/api/people/65/",
			"https://swapi.dev/api/people/66/",
			"https://swapi.dev/api/people/67/",
			"https://swapi.dev/api/people/68/",
			"https://swapi.dev/api/people/69/",
			"https://swapi.dev/api/people/70/",
			"https://swapi.dev/api/people/71/",
			"https://swapi.dev/api/people/72/",
			"https://swapi.dev/api/people/73/",
			"https://swapi.dev/api/people/74/",
			"https://swapi.dev/api/people/75/",
			"https://swapi.dev/api/people/76/",
			"https://swapi.dev/api/people/77/",
			"https://swapi.dev/api/people/78/",
			"https://swapi.dev/api/people/82/",
		],
		planets: [
			"https://swapi.dev/api/planets/1/",
			"https://swapi.dev/api/planets/8/",
			"https://swapi.dev/api/planets/9/",
			"https://swapi.dev/api/planets/10/",
			"https://swapi.dev/api/planets/11/",
		],
		starships: [
			"https://swapi.dev/api/starships/21/",
			"https://swapi.dev/api/starships/32/",
			"https://swapi.dev/api/starships/39/",
			"https://swapi.dev/api/starships/43/",
			"https://swapi.dev/api/starships/47/",
			"https://swapi.dev/api/starships/48/",
			"https://swapi.dev/api/starships/49/",
			"https://swapi.dev/api/starships/52/",
			"https://swapi.dev/api/starships/58/",
		],
		vehicles: [
			"https://swapi.dev/api/vehicles/4/",
			"https://swapi.dev/api/vehicles/44/",
			"https://swapi.dev/api/vehicles/45/",
			"https://swapi.dev/api/vehicles/46/",
			"https://swapi.dev/api/vehicles/50/",
			"https://swapi.dev/api/vehicles/51/",
			"https://swapi.dev/api/vehicles/53/",
			"https://swapi.dev/api/vehicles/54/",
			"https://swapi.dev/api/vehicles/55/",
			"https://swapi.dev/api/vehicles/56/",
			"https://swapi.dev/api/vehicles/57/",
		],
		species: [
			"https://swapi.dev/api/species/1/",
			"https://swapi.dev/api/species/2/",
			"https://swapi.dev/api/species/6/",
			"https://swapi.dev/api/species/12/",
			"https://swapi.dev/api/species/13/",
			"https://swapi.dev/api/species/15/",
			"https://swapi.dev/api/species/28/",
			"https://swapi.dev/api/species/29/",
			"https://swapi.dev/api/species/30/",
			"https://swapi.dev/api/species/31/",
			"https://swapi.dev/api/species/32/",
			"https://swapi.dev/api/species/33/",
			"https://swapi.dev/api/species/34/",
			"https://swapi.dev/api/species/35/",
		],
		created: "2014-12-20T10:57:57.886000Z",
		edited: "2014-12-20T20:18:48.516000Z",
		url: "https://swapi.dev/api/films/5/",
	},
	{
		title: "Revenge of the Sith",
		episode_id: 3,
		opening_crawl:
			"War! The Republic is crumbling\r\nunder attacks by the ruthless\r\nSith Lord, Count Dooku.\r\nThere are heroes on both sides.\r\nEvil is everywhere.\r\n\r\nIn a stunning move, the\r\nfiendish droid leader, General\r\nGrievous, has swept into the\r\nRepublic capital and kidnapped\r\nChancellor Palpatine, leader of\r\nthe Galactic Senate.\r\n\r\nAs the Separatist Droid Army\r\nattempts to flee the besieged\r\ncapital with their valuable\r\nhostage, two Jedi Knights lead a\r\ndesperate mission to rescue the\r\ncaptive Chancellor....",
		director: "George Lucas",
		producer: "Rick McCallum",
		release_date: "2005-05-19",
		characters: [
			"https://swapi.dev/api/people/1/",
			"https://swapi.dev/api/people/2/",
			"https://swapi.dev/api/people/3/",
			"https://swapi.dev/api/people/4/",
			"https://swapi.dev/api/people/5/",
			"https://swapi.dev/api/people/6/",
			"https://swapi.dev/api/people/7/",
			"https://swapi.dev/api/people/10/",
			"https://swapi.dev/api/people/11/",
			"https://swapi.dev/api/people/12/",
			"https://swapi.dev/api/people/13/",
			"https://swapi.dev/api/people/20/",
			"https://swapi.dev/api/people/21/",
			"https://swapi.dev/api/people/33/",
			"https://swapi.dev/api/people/35/",
			"https://swapi.dev/api/people/46/",
			"https://swapi.dev/api/people/51/",
			"https://swapi.dev/api/people/52/",
			"https://swapi.dev/api/people/53/",
			"https://swapi.dev/api/people/54/",
			"https://swapi.dev/api/people/55/",
			"https://swapi.dev/api/people/56/",
			"https://swapi.dev/api/people/58/",
			"https://swapi.dev/api/people/63/",
			"https://swapi.dev/api/people/64/",
			"https://swapi.dev/api/people/67/",
			"https://swapi.dev/api/people/68/",
			"https://swapi.dev/api/people/75/",
			"https://swapi.dev/api/people/78/",
			"https://swapi.dev/api/people/79/",
			"https://swapi.dev/api/people/80/",
			"https://swapi.dev/api/people/81/",
			"https://swapi.dev/api/people/82/",
			"https://swapi.dev/api/people/83/",
		],
		planets: [
			"https://swapi.dev/api/planets/1/",
			"https://swapi.dev/api/planets/2/",
			"https://swapi.dev/api/planets/5/",
			"https://swapi.dev/api/planets/8/",
			"https://swapi.dev/api/planets/9/",
			"https://swapi.dev/api/planets/12/",
			"https://swapi.dev/api/planets/13/",
			"https://swapi.dev/api/planets/14/",
			"https://swapi.dev/api/planets/15/",
			"https://swapi.dev/api/planets/16/",
			"https://swapi.dev/api/planets/17/",
			"https://swapi.dev/api/planets/18/",
			"https://swapi.dev/api/planets/19/",
		],
		starships: [
			"https://swapi.dev/api/starships/2/",
			"https://swapi.dev/api/starships/32/",
			"https://swapi.dev/api/starships/48/",
			"https://swapi.dev/api/starships/59/",
			"https://swapi.dev/api/starships/61/",
			"https://swapi.dev/api/starships/63/",
			"https://swapi.dev/api/starships/64/",
			"https://swapi.dev/api/starships/65/",
			"https://swapi.dev/api/starships/66/",
			"https://swapi.dev/api/starships/68/",
			"https://swapi.dev/api/starships/74/",
			"https://swapi.dev/api/starships/75/",
		],
		vehicles: [
			"https://swapi.dev/api/vehicles/33/",
			"https://swapi.dev/api/vehicles/50/",
			"https://swapi.dev/api/vehicles/53/",
			"https://swapi.dev/api/vehicles/56/",
			"https://swapi.dev/api/vehicles/60/",
			"https://swapi.dev/api/vehicles/62/",
			"https://swapi.dev/api/vehicles/67/",
			"https://swapi.dev/api/vehicles/69/",
			"https://swapi.dev/api/vehicles/70/",
			"https://swapi.dev/api/vehicles/71/",
			"https://swapi.dev/api/vehicles/72/",
			"https://swapi.dev/api/vehicles/73/",
			"https://swapi.dev/api/vehicles/76/",
		],
		species: [
			"https://swapi.dev/api/species/1/",
			"https://swapi.dev/api/species/2/",
			"https://swapi.dev/api/species/3/",
			"https://swapi.dev/api/species/6/",
			"https://swapi.dev/api/species/15/",
			"https://swapi.dev/api/species/19/",
			"https://swapi.dev/api/species/20/",
			"https://swapi.dev/api/species/23/",
			"https://swapi.dev/api/species/24/",
			"https://swapi.dev/api/species/25/",
			"https://swapi.dev/api/species/26/",
			"https://swapi.dev/api/species/27/",
			"https://swapi.dev/api/species/28/",
			"https://swapi.dev/api/species/29/",
			"https://swapi.dev/api/species/30/",
			"https://swapi.dev/api/species/33/",
			"https://swapi.dev/api/species/34/",
			"https://swapi.dev/api/species/35/",
			"https://swapi.dev/api/species/36/",
			"https://swapi.dev/api/species/37/",
		],
		created: "2014-12-20T18:49:38.403000Z",
		edited: "2014-12-20T20:47:52.073000Z",
		url: "https://swapi.dev/api/films/6/",
	},
	{
		name: "Kamino",
		rotation_period: "27",
		orbital_period: "463",
		diameter: "19720",
		climate: "temperate",
		gravity: "1 standard",
		terrain: "ocean",
		surface_water: "100",
		population: "1000000000",
		residents: [
			"https://swapi.dev/api/people/22/",
			"https://swapi.dev/api/people/72/",
			"https://swapi.dev/api/people/73/",
		],
		films: ["https://swapi.dev/api/films/5/"],
		created: "2014-12-10T12:45:06.577000Z",
		edited: "2014-12-20T20:58:18.434000Z",
		url: "https://swapi.dev/api/planets/10/",
	},
	{
		name: "Eriadu",
		rotation_period: "24",
		orbital_period: "360",
		diameter: "13490",
		climate: "polluted",
		gravity: "1 standard",
		terrain: "cityscape",
		surface_water: "unknown",
		population: "22000000000",
		residents: ["https://swapi.dev/api/people/12/"],
		films: [],
		created: "2014-12-10T16:26:54.384000Z",
		edited: "2014-12-20T20:58:18.454000Z",
		url: "https://swapi.dev/api/planets/21/",
	},
	{
		name: "Serenno",
		rotation_period: "unknown",
		orbital_period: "unknown",
		diameter: "unknown",
		climate: "unknown",
		gravity: "unknown",
		terrain: "rainforests, rivers, mountains",
		surface_water: "unknown",
		population: "unknown",
		residents: ["https://swapi.dev/api/people/67/"],
		films: [],
		created: "2014-12-20T16:52:13.357000Z",
		edited: "2014-12-20T20:58:18.510000Z",
		url: "https://swapi.dev/api/planets/52/",
	},
	{
		name: "TIE Advanced x1",
		model: "Twin Ion Engine Advanced x1",
		manufacturer: "Sienar Fleet Systems",
		cost_in_credits: "unknown",
		length: "9.2",
		max_atmosphering_speed: "1200",
		crew: "1",
		passengers: "0",
		cargo_capacity: "150",
		consumables: "5 days",
		hyperdrive_rating: "1.0",
		MGLT: "105",
		starship_class: "Starfighter",
		pilots: ["https://swapi.dev/api/people/4/"],
		films: ["https://swapi.dev/api/films/1/"],
		created: "2014-12-12T11:21:32.991000Z",
		edited: "2014-12-20T21:23:49.889000Z",
		url: "https://swapi.dev/api/starships/13/",
	},
	{
		name: "Jedi Interceptor",
		model: "Eta-2 Actis-class light interceptor",
		manufacturer: "Kuat Systems Engineering",
		cost_in_credits: "320000",
		length: "5.47",
		max_atmosphering_speed: "1500",
		crew: "1",
		passengers: "0",
		cargo_capacity: "60",
		consumables: "2 days",
		hyperdrive_rating: "1.0",
		MGLT: "unknown",
		starship_class: "starfighter",
		pilots: ["https://swapi.dev/api/people/10/", "https://swapi.dev/api/people/11/"],
		films: ["https://swapi.dev/api/films/6/"],
		created: "2014-12-20T19:56:57.468000Z",
		edited: "2014-12-20T21:23:49.951000Z",
		url: "https://swapi.dev/api/starships/65/",
	},
	{
		name: "Naboo star skiff",
		model: "J-type star skiff",
		manufacturer: "Theed Palace Space Vessel Engineering Corps/Nubia Star Drives, Incorporated",
		cost_in_credits: "unknown",
		length: "29.2",
		max_atmosphering_speed: "1050",
		crew: "3",
		passengers: "3",
		cargo_capacity: "unknown",
		consumables: "unknown",
		hyperdrive_rating: "0.5",
		MGLT: "unknown",
		starship_class: "yacht",
		pilots: ["https://swapi.dev/api/people/10/", "https://swapi.dev/api/people/35/"],
		films: ["https://swapi.dev/api/films/6/"],
		created: "2014-12-20T19:55:15.396000Z",
		edited: "2014-12-20T21:23:49.948000Z",
		url: "https://swapi.dev/api/starships/64/",
	},
	{
		name: "Trade Federation cruiser",
		model: "Providence-class carrier/destroyer",
		manufacturer: "Rendili StarDrive, Free Dac Volunteers Engineering corps.",
		cost_in_credits: "125000000",
		length: "1088",
		max_atmosphering_speed: "1050",
		crew: "600",
		passengers: "48247",
		cargo_capacity: "50000000",
		consumables: "4 years",
		hyperdrive_rating: "1.5",
		MGLT: "unknown",
		starship_class: "capital ship",
		pilots: ["https://swapi.dev/api/people/10/", "https://swapi.dev/api/people/11/"],
		films: ["https://swapi.dev/api/films/6/"],
		created: "2014-12-20T19:40:21.902000Z",
		edited: "2014-12-20T21:23:49.941000Z",
		url: "https://swapi.dev/api/starships/59/",
	},
	{
		name: "Slave 1",
		model: "Firespray-31-class patrol and attack",
		manufacturer: "Kuat Systems Engineering",
		cost_in_credits: "unknown",
		length: "21.5",
		max_atmosphering_speed: "1000",
		crew: "1",
		passengers: "6",
		cargo_capacity: "70000",
		consumables: "1 month",
		hyperdrive_rating: "3.0",
		MGLT: "70",
		starship_class: "Patrol craft",
		pilots: ["https://swapi.dev/api/people/22/"],
		films: ["https://swapi.dev/api/films/2/", "https://swapi.dev/api/films/5/"],
		created: "2014-12-15T13:00:56.332000Z",
		edited: "2014-12-20T21:23:49.897000Z",
		url: "https://swapi.dev/api/starships/21/",
	},
	{
		name: "Millennium Falcon",
		model: "YT-1300 light freighter",
		manufacturer: "Corellian Engineering Corporation",
		cost_in_credits: "100000",
		length: "34.37",
		max_atmosphering_speed: "1050",
		crew: "4",
		passengers: "6",
		cargo_capacity: "100000",
		consumables: "2 months",
		hyperdrive_rating: "0.5",
		MGLT: "75",
		starship_class: "Light freighter",
		pilots: [
			"https://swapi.dev/api/people/13/",
			"https://swapi.dev/api/people/14/",
			"https://swapi.dev/api/people/25/",
			"https://swapi.dev/api/people/31/",
		],
		films: [
			"https://swapi.dev/api/films/1/",
			"https://swapi.dev/api/films/2/",
			"https://swapi.dev/api/films/3/",
		],
		created: "2014-12-10T16:59:45.094000Z",
		edited: "2014-12-20T21:23:49.880000Z",
		url: "https://swapi.dev/api/starships/10/",
	},
	{
		name: "Imperial shuttle",
		model: "Lambda-class T-4a shuttle",
		manufacturer: "Sienar Fleet Systems",
		cost_in_credits: "240000",
		length: "20",
		max_atmosphering_speed: "850",
		crew: "6",
		passengers: "20",
		cargo_capacity: "80000",
		consumables: "2 months",
		hyperdrive_rating: "1.0",
		MGLT: "50",
		starship_class: "Armed government transport",
		pilots: [
			"https://swapi.dev/api/people/1/",
			"https://swapi.dev/api/people/13/",
			"https://swapi.dev/api/people/14/",
		],
		films: ["https://swapi.dev/api/films/2/", "https://swapi.dev/api/films/3/"],
		created: "2014-12-15T13:04:47.235000Z",
		edited: "2014-12-20T21:23:49.900000Z",
		url: "https://swapi.dev/api/starships/22/",
	},
	{
		name: "Belbullab-22 starfighter",
		model: "Belbullab-22 starfighter",
		manufacturer: "Feethan Ottraw Scalable Assemblies",
		cost_in_credits: "168000",
		length: "6.71",
		max_atmosphering_speed: "1100",
		crew: "1",
		passengers: "0",
		cargo_capacity: "140",
		consumables: "7 days",
		hyperdrive_rating: "6",
		MGLT: "unknown",
		starship_class: "starfighter",
		pilots: ["https://swapi.dev/api/people/10/", "https://swapi.dev/api/people/79/"],
		films: ["https://swapi.dev/api/films/6/"],
		created: "2014-12-20T20:38:05.031000Z",
		edited: "2014-12-20T21:23:49.959000Z",
		url: "https://swapi.dev/api/starships/74/",
	},
	{
		name: "Jedi starfighter",
		model: "Delta-7 Aethersprite-class interceptor",
		manufacturer: "Kuat Systems Engineering",
		cost_in_credits: "180000",
		length: "8",
		max_atmosphering_speed: "1150",
		crew: "1",
		passengers: "0",
		cargo_capacity: "60",
		consumables: "7 days",
		hyperdrive_rating: "1.0",
		MGLT: "unknown",
		starship_class: "Starfighter",
		pilots: ["https://swapi.dev/api/people/10/", "https://swapi.dev/api/people/58/"],
		films: ["https://swapi.dev/api/films/5/", "https://swapi.dev/api/films/6/"],
		created: "2014-12-20T17:35:23.906000Z",
		edited: "2014-12-20T21:23:49.930000Z",
		url: "https://swapi.dev/api/starships/48/",
	},
	{
		name: "Scimitar",
		model: "Star Courier",
		manufacturer: "Republic Sienar Systems",
		cost_in_credits: "55000000",
		length: "26.5",
		max_atmosphering_speed: "1180",
		crew: "1",
		passengers: "6",
		cargo_capacity: "2500000",
		consumables: "30 days",
		hyperdrive_rating: "1.5",
		MGLT: "unknown",
		starship_class: "Space Transport",
		pilots: ["https://swapi.dev/api/people/44/"],
		films: ["https://swapi.dev/api/films/4/"],
		created: "2014-12-20T09:39:56.116000Z",
		edited: "2014-12-20T21:23:49.922000Z",
		url: "https://swapi.dev/api/starships/41/",
	},
	{
		name: "X-wing",
		model: "T-65 X-wing",
		manufacturer: "Incom Corporation",
		cost_in_credits: "149999",
		length: "12.5",
		max_atmosphering_speed: "1050",
		crew: "1",
		passengers: "0",
		cargo_capacity: "110",
		consumables: "1 week",
		hyperdrive_rating: "1.0",
		MGLT: "100",
		starship_class: "Starfighter",
		pilots: [
			"https://swapi.dev/api/people/1/",
			"https://swapi.dev/api/people/9/",
			"https://swapi.dev/api/people/18/",
			"https://swapi.dev/api/people/19/",
		],
		films: [
			"https://swapi.dev/api/films/1/",
			"https://swapi.dev/api/films/2/",
			"https://swapi.dev/api/films/3/",
		],
		created: "2014-12-12T11:19:05.340000Z",
		edited: "2014-12-20T21:23:49.886000Z",
		url: "https://swapi.dev/api/starships/12/",
	},
	{
		name: "AT-ST",
		model: "All Terrain Scout Transport",
		manufacturer: "Kuat Drive Yards, Imperial Department of Military Research",
		cost_in_credits: "unknown",
		length: "2",
		max_atmosphering_speed: "90",
		crew: "2",
		passengers: "0",
		cargo_capacity: "200",
		consumables: "none",
		vehicle_class: "walker",
		pilots: ["https://swapi.dev/api/people/13/"],
		films: ["https://swapi.dev/api/films/2/", "https://swapi.dev/api/films/3/"],
		created: "2014-12-15T12:46:42.384000Z",
		edited: "2014-12-20T21:30:21.679000Z",
		url: "https://swapi.dev/api/vehicles/19/",
	},
	{
		name: "Imperial Speeder Bike",
		model: "74-Z speeder bike",
		manufacturer: "Aratech Repulsor Company",
		cost_in_credits: "8000",
		length: "3",
		max_atmosphering_speed: "360",
		crew: "1",
		passengers: "1",
		cargo_capacity: "4",
		consumables: "1 day",
		vehicle_class: "speeder",
		pilots: ["https://swapi.dev/api/people/1/", "https://swapi.dev/api/people/5/"],
		films: ["https://swapi.dev/api/films/3/"],
		created: "2014-12-18T11:20:04.625000Z",
		edited: "2014-12-20T21:30:21.693000Z",
		url: "https://swapi.dev/api/vehicles/30/",
	},
	{
		name: "Sith speeder",
		model: "FC-20 speeder bike",
		manufacturer: "Razalon",
		cost_in_credits: "4000",
		length: "1.5",
		max_atmosphering_speed: "180",
		crew: "1",
		passengers: "0",
		cargo_capacity: "2",
		consumables: "unknown",
		vehicle_class: "speeder",
		pilots: ["https://swapi.dev/api/people/44/"],
		films: ["https://swapi.dev/api/films/4/"],
		created: "2014-12-20T10:09:56.095000Z",
		edited: "2014-12-20T21:30:21.712000Z",
		url: "https://swapi.dev/api/vehicles/42/",
	},
	{
		name: "Tribubble bongo",
		model: "Tribubble bongo",
		manufacturer: "Otoh Gunga Bongameken Cooperative",
		cost_in_credits: "unknown",
		length: "15",
		max_atmosphering_speed: "85",
		crew: "1",
		passengers: "2",
		cargo_capacity: "1600",
		consumables: "unknown",
		vehicle_class: "submarine",
		pilots: ["https://swapi.dev/api/people/10/", "https://swapi.dev/api/people/32/"],
		films: ["https://swapi.dev/api/films/4/"],
		created: "2014-12-19T17:37:37.924000Z",
		edited: "2014-12-20T21:30:21.710000Z",
		url: "https://swapi.dev/api/vehicles/38/",
	},
	{
		name: "Snowspeeder",
		model: "t-47 airspeeder",
		manufacturer: "Incom corporation",
		cost_in_credits: "unknown",
		length: "4.5",
		max_atmosphering_speed: "650",
		crew: "2",
		passengers: "0",
		cargo_capacity: "10",
		consumables: "none",
		vehicle_class: "airspeeder",
		pilots: ["https://swapi.dev/api/people/1/", "https://swapi.dev/api/people/18/"],
		films: ["https://swapi.dev/api/films/2/"],
		created: "2014-12-15T12:22:12Z",
		edited: "2014-12-20T21:30:21.672000Z",
		url: "https://swapi.dev/api/vehicles/14/",
	},
	{
		name: "Flitknot speeder",
		model: "Flitknot speeder",
		manufacturer: "Huppla Pasa Tisc Shipwrights Collective",
		cost_in_credits: "8000",
		length: "2",
		max_atmosphering_speed: "634",
		crew: "1",
		passengers: "0",
		cargo_capacity: "unknown",
		consumables: "unknown",
		vehicle_class: "speeder",
		pilots: ["https://swapi.dev/api/people/67/"],
		films: ["https://swapi.dev/api/films/5/"],
		created: "2014-12-20T18:15:20.312000Z",
		edited: "2014-12-20T21:30:21.735000Z",
		url: "https://swapi.dev/api/vehicles/55/",
	},
	{
		name: "Tsmeu-6 personal wheel bike",
		model: "Tsmeu-6 personal wheel bike",
		manufacturer: "Z-Gomot Ternbuell Guppat Corporation",
		cost_in_credits: "15000",
		length: "3.5",
		max_atmosphering_speed: "330",
		crew: "1",
		passengers: "1",
		cargo_capacity: "10",
		consumables: "none",
		vehicle_class: "wheeled walker",
		pilots: ["https://swapi.dev/api/people/79/"],
		films: ["https://swapi.dev/api/films/6/"],
		created: "2014-12-20T19:43:54.870000Z",
		edited: "2014-12-20T21:30:21.745000Z",
		url: "https://swapi.dev/api/vehicles/60/",
	},
];

const USE_FALLBACK = true;

const fetchData = (url) => {
	const fallback = fallbackData.find((data) => data.url === url);
	if (USE_FALLBACK && fallback) {
		return Promise.resolve(fallback);
	}
	return fetch(url)
		.then((res) => res.json())
		.then((data) => {
			if (USE_FALLBACK) {
				console.log("did not have the following data:");
				console.log(data);
			}
			return data;
		});
};
